### ISSUE TITLE
Confusion about MRSA and normal SA

### ISSUE THREAD

**Issue by wzic** [aim-uofa/FreeCustom#6]
![image](https://github.com/aim-uofa/FreeCustom/assets/55567040/eb60b24b-48a4-420c-8377-c85782918cc3)

Hi!
It seems that, besides the MRSA (done in line 125 and 126), there is also normal SA (done in line 132) and it is particularly for reference concepts. May I know why there exists a normal SA for ref concepts beyond MRSA ? Can't MRSA handle everything ?

**Comment by dingangui** [comment]
normal SA in line 132 is for the concept reference path, and MRSA in lines 125 and 126 is for the concept composition path~

**Comment by wzic** [comment]
So it means the denoising of reference images should be done simultaneously with the denoising of the composition image ? I thought that the concept reference path denoising is done separately, so as to prepare for the ref self-attention KVs in advance. What will happen if the two paths are done separately ?

**Comment by dingangui** [comment]
1. In our current setting, the denoising of reference images is done simultaneously with the denoising of the composition image, that's why we have MRSA and the original SA at the same time.
2. The concept reference path denoising can be done separately, but we didn't do that. 
3. If you want to prepare for the ref self-attention KVs in advance, what you need is the original self-attention module in the denoising process, the proposed MRSA is only for the concept composition path.
